@AIAgent.Host_HostAddress = http://localhost:5001

POST {{AIAgent.Host_HostAddress}}/ContosoTravelAgent/v1/chat/completions
Content-Type: application/json

{
  "model": "gpt-4o",
  "messages": [
    {
      "role": "user",
      "content": "Hi! Can you help me plan a trip?"
    }
  ]
}

### OpenAI Chat Completions API with History
POST {{AIAgent.Host_HostAddress}}/ContosoTravelAgent/v1/chat/completions
Content-Type: application/json

{
  "model": "gpt-4o",
  "messages": [
    {
      "role": "user",
      "content": "Hi! Can you help me plan a trip?"
    },
    {
      "role": "assistant",
      "content": "Hello! I'd be happy to help you plan your next trip. To get started, could you please tell me a bit about your travel preferences? For example, what kind of activities do you enjoy, and do you have any specific destinations in mind?"
    },
    {
      "role": "user",
      "content": "I love snorkeling and diving. My budget is around $3000"
    }
  ]
}